version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
  docker:
      - image: circleci/node:14

    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
