version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: "circleci/node:14"
    steps:
      - checkout
      - node/install-packages:
          cache-version: "1"
          pkg-manager: "npm"
      - run: npm run build
      - run: npm test
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
