version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-version: "v2" # This line is added to update the cache version, which effectively clears the cache
          pkg-manager: npm
      - run: npm run build
workflows:
  build_deploy:
    jobs:
      - build
